### ISSUE TITLE
How did you get the dataset

### ISSUE THREAD

**Issue by alexbuyval** [WERush/BridgeGAN#2]
@WERush Thank you for the excellent work!

Could you describe the procedure of how to get the dataset for your approach?

Regards,
Alex

**Comment by WERush** [comment]
Hi, @alexbuyval ,

For the frontal-view images and birdview images, we got them from this [URL](http://imagelab.ing.unimore.it/scene-awareness), which are extracted from GTAV.

For the homography images, we use the opencv to get this intermediate view. You can refer this [URL](https://www.learnopencv.com/homography-examples-using-opencv-python-c/).
We also provide the full dataset that we used in our experiments (please check the README).

**Comment by alexbuyval** [comment]
@WERush Thank you very much!

These links are very useful.
